#!/usr/bin/env bash
# Materialize Secret-backed demo credentials into one gitignored, mode-0600
# env file. Deployment-specific URLs and resource overrides come from the
# optional .local/k8s/demo-access.env file. Secret values are never printed.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
config_path="${DEMO_ACCESS_CONFIG:-$repo_root/.local/k8s/demo-access.env}"
output_path="$repo_root/.local/k8s/demo-credentials.env"

if [[ $# -ne 0 ]]; then
    echo "ERROR: configure this helper with $config_path, not command-line arguments." >&2
    exit 2
fi

if [[ -f "$config_path" ]]; then
    # This is a trusted, operator-owned shell environment file under .local/.
    # shellcheck disable=SC1090
    source "$config_path"
fi

: "${IDENTITY_NAMESPACE:=identity}"
: "${KEYCLOAK_BOOTSTRAP_RESOURCE:=keycloak-bootstrap-user}"
: "${KEYCLOAK_ADMIN_CREDENTIAL_RESOURCE:=keycloak-admin-credentials}"
: "${OBSERVABILITY_NAMESPACE:=observability}"
: "${GRAFANA_CREDENTIAL_RESOURCE:=kube-prom-stack-grafana}"
: "${PHOENIX_CREDENTIAL_RESOURCE:=phoenix-secret}"
: "${APPLICATION_NAMESPACE:=llm-chat}"
: "${ELASTIC_CREDENTIAL_RESOURCE:=elastic-credentials}"

command -v kubectl >/dev/null 2>&1 || {
    echo "ERROR: kubectl is required." >&2
    exit 1
}

mkdir -p "$(dirname "$output_path")"
umask 077
temporary_path="$(mktemp "$(dirname "$output_path")/.demo-credentials.XXXXXX")"
trap 'rm -f "$temporary_path"' EXIT

secret_exists() {
    kubectl -n "$1" get secret "$2" >/dev/null 2>&1
}

secret_value() {
    local namespace="$1"
    local secret_name="$2"
    local key="$3"
    kubectl -n "$namespace" get secret "$secret_name" \
        -o go-template --template="{{ index .data \"$key\" | base64decode }}"
}

write_env() {
    local name="$1"
    local value="$2"
    printf '%s=' "$name"
    printf '%q\n' "$value"
}

write_url_if_configured() {
    local name="$1"
    local value="${!name:-}"
    if [[ -n "$value" ]]; then
        write_env "$name" "$value"
    fi
}

tenantchat_username="$(secret_value "$IDENTITY_NAMESPACE" "$KEYCLOAK_BOOTSTRAP_RESOURCE" username)"
tenantchat_password="$(secret_value "$IDENTITY_NAMESPACE" "$KEYCLOAK_BOOTSTRAP_RESOURCE" password)"
tenantchat_email="$(secret_value "$IDENTITY_NAMESPACE" "$KEYCLOAK_BOOTSTRAP_RESOURCE" email)"
keycloak_username="$(secret_value "$IDENTITY_NAMESPACE" "$KEYCLOAK_ADMIN_CREDENTIAL_RESOURCE" username)"
keycloak_password="$(secret_value "$IDENTITY_NAMESPACE" "$KEYCLOAK_ADMIN_CREDENTIAL_RESOURCE" password)"
grafana_username="$(secret_value "$OBSERVABILITY_NAMESPACE" "$GRAFANA_CREDENTIAL_RESOURCE" admin-user)"
grafana_password="$(secret_value "$OBSERVABILITY_NAMESPACE" "$GRAFANA_CREDENTIAL_RESOURCE" admin-password)"

{
    echo "# Generated by scripts/prepare_demo_credentials.sh"
    echo "# Contains demo credentials. Do not commit, paste, or attach this file."
    write_url_if_configured VISITOR_URL
    write_url_if_configured TENANTCHAT_ADMIN_URL
    write_env TENANTCHAT_ADMIN_USERNAME "$tenantchat_username"
    write_env TENANTCHAT_ADMIN_PASSWORD "$tenantchat_password"
    write_env TENANTCHAT_ADMIN_EMAIL "$tenantchat_email"
    write_url_if_configured KEYCLOAK_URL
    write_env KEYCLOAK_ADMIN_USERNAME "$keycloak_username"
    write_env KEYCLOAK_ADMIN_PASSWORD "$keycloak_password"
    write_url_if_configured GRAFANA_URL
    write_env GRAFANA_USERNAME "$grafana_username"
    write_env GRAFANA_PASSWORD "$grafana_password"
    write_url_if_configured PROMETHEUS_URL
    write_url_if_configured TEMPO_URL
    write_url_if_configured MLFLOW_URL
    write_url_if_configured KAFKA_UI_URL
    write_url_if_configured KUBERNETES_DASHBOARD_URL
    write_url_if_configured KIBANA_URL

    if secret_exists "$OBSERVABILITY_NAMESPACE" "$PHOENIX_CREDENTIAL_RESOURCE"; then
        write_url_if_configured PHOENIX_URL
        write_env PHOENIX_USERNAME "admin@localhost"
        write_env PHOENIX_INITIAL_PASSWORD \
            "$(secret_value "$OBSERVABILITY_NAMESPACE" "$PHOENIX_CREDENTIAL_RESOURCE" PHOENIX_DEFAULT_ADMIN_INITIAL_PASSWORD)"
    fi

    if secret_exists "$APPLICATION_NAMESPACE" "$ELASTIC_CREDENTIAL_RESOURCE"; then
        write_env ELASTIC_USERNAME \
            "$(secret_value "$APPLICATION_NAMESPACE" "$ELASTIC_CREDENTIAL_RESOURCE" username)"
        write_env ELASTIC_PASSWORD \
            "$(secret_value "$APPLICATION_NAMESPACE" "$ELASTIC_CREDENTIAL_RESOURCE" password)"
    fi
} >"$temporary_path"

chmod 600 "$temporary_path"
mv "$temporary_path" "$output_path"
trap - EXIT

echo "Wrote demo credentials to $output_path (mode 0600)."
echo "Values were not printed. The file is under the gitignored .local/ tree."
