"""Framework-free domain model for the tenant chat platform.

Nothing in this package may import a web framework, ORM, agent framework, or
model SDK. See ``packages/core/pyproject.toml`` for why, and
``tests/test_architecture_invariants.py`` for the check that enforces it.
"""

from tenantchat.core.catalog import ServiceCatalog, ServiceDefinition, normalize_term
from tenantchat.core.commands import (
    BookingCommand,
    HandoffCommand,
    HandoffReason,
    LeadCommand,
    LeadUrgency,
)
from tenantchat.core.contact import Contact, ContactKind
from tenantchat.core.errors import (
    BookingNotPermittedError,
    ConflictError,
    DomainError,
    InvalidContactError,
    InvalidVersionTransitionError,
    LeadCaptureNotPermittedError,
    MissingRequiredFieldsError,
    NotFoundError,
    PolicyViolationError,
    PricingNotPermittedError,
    SlotUnavailableError,
    UnknownServiceError,
    ValidationError,
)
from tenantchat.core.fields import RequiredField
from tenantchat.core.knowledge import (
    ApprovalPlan,
    ContentChecksum,
    DocumentVersion,
    ExpiryPlan,
    KnowledgeDocument,
    KnowledgeDomain,
    KnowledgeSource,
    PublicationPlan,
    PublicDocumentView,
    RetrievalAudience,
    RetrievalContext,
    SourceKind,
    Visibility,
)
from tenantchat.core.lifecycle import IndexingState, VersionState
from tenantchat.core.ports import (
    AssistantTurn,
    AvailabilityProvider,
    BookingConfirmation,
    BookingService,
    CommittedEffect,
    ConversationRuntime,
    HandoffService,
    HandoffTicket,
    IdempotencyKey,
    LeadReceipt,
    LeadService,
    TenantPolicySource,
)
from tenantchat.core.tenant import PricingPolicy, PublicTenantView, TenantPolicy

__all__ = [
    "ApprovalPlan",
    "AssistantTurn",
    "AvailabilityProvider",
    "BookingCommand",
    "BookingConfirmation",
    "BookingNotPermittedError",
    "BookingService",
    "CommittedEffect",
    "ConflictError",
    "Contact",
    "ContactKind",
    "ContentChecksum",
    "ConversationRuntime",
    "DocumentVersion",
    "DomainError",
    "ExpiryPlan",
    "HandoffCommand",
    "HandoffReason",
    "HandoffService",
    "HandoffTicket",
    "IdempotencyKey",
    "IndexingState",
    "InvalidContactError",
    "InvalidVersionTransitionError",
    "KnowledgeDocument",
    "KnowledgeDomain",
    "KnowledgeSource",
    "LeadCaptureNotPermittedError",
    "LeadCommand",
    "LeadReceipt",
    "LeadService",
    "LeadUrgency",
    "MissingRequiredFieldsError",
    "NotFoundError",
    "PolicyViolationError",
    "PricingNotPermittedError",
    "PricingPolicy",
    "PublicDocumentView",
    "PublicTenantView",
    "PublicationPlan",
    "RequiredField",
    "RetrievalAudience",
    "RetrievalContext",
    "ServiceCatalog",
    "ServiceDefinition",
    "SlotUnavailableError",
    "SourceKind",
    "TenantPolicy",
    "TenantPolicySource",
    "UnknownServiceError",
    "ValidationError",
    "VersionState",
    "Visibility",
    "normalize_term",
]
