"""Framework-free domain model for the tenant chat platform.

Nothing in this package may import a web framework, ORM, agent framework, or
model SDK. See ``packages/core/pyproject.toml`` for why, and
``tests/test_architecture_invariants.py`` for the check that enforces it.
"""

from tenantchat.core.catalog import ServiceCatalog, ServiceDefinition, normalize_term
from tenantchat.core.citations import Citation
from tenantchat.core.claims import (
    Claim,
    ClaimKind,
    ClaimValidation,
    ClaimVerdict,
    sensitive_claims,
    validate_sensitive_claims,
)
from tenantchat.core.commands import (
    BookingCommand,
    HandoffCommand,
    HandoffReason,
    LeadCommand,
    LeadUrgency,
)
from tenantchat.core.contact import Contact, ContactKind
from tenantchat.core.errors import (
    BookingNotPermittedError,
    ConflictError,
    DomainError,
    ExpiredVisitorCredentialError,
    InvalidContactError,
    InvalidVersionTransitionError,
    InvalidVisitorCredentialError,
    LeadCaptureNotPermittedError,
    MissingRequiredFieldsError,
    NotFoundError,
    PolicyViolationError,
    PricingNotPermittedError,
    SlotUnavailableError,
    UnknownServiceError,
    ValidationError,
)
from tenantchat.core.fields import RequiredField
from tenantchat.core.guards import (
    ToolPermissionVerdict,
    ToolRefusal,
    tool_permission,
)
from tenantchat.core.indexing import (
    INDEX_LAG_THRESHOLD,
    GenerationStatus,
    IndexGeneration,
    IndexingFault,
    IndexIntegrityFinding,
)
from tenantchat.core.knowledge import (
    ApprovalPlan,
    ContentChecksum,
    DocumentVersion,
    ExpiryPlan,
    KnowledgeDocument,
    KnowledgeDomain,
    KnowledgeSource,
    PublicationPlan,
    PublicDocumentView,
    RetrievalAudience,
    RetrievalContext,
    SourceKind,
    Visibility,
)
from tenantchat.core.lifecycle import IndexingState, VersionState
from tenantchat.core.ports import (
    AssistantTurn,
    AvailabilityProvider,
    BookingConfirmation,
    BookingService,
    CommittedEffect,
    ConversationRuntime,
    EvidenceBundle,
    EvidenceItem,
    EvidenceSource,
    EvidenceUnavailableError,
    HandoffService,
    HandoffTicket,
    IdempotencyKey,
    LeadReceipt,
    LeadService,
    TenantPolicySource,
)
from tenantchat.core.safety import QuarantineReviewPlan, SafetyState
from tenantchat.core.slots import OfferedSlot
from tenantchat.core.tenant import PricingPolicy, PublicTenantView, TenantPolicy
from tenantchat.core.visitor_session import (
    HmacVisitorCredentialSigner,
    VisitorCredential,
    VisitorCredentialSigner,
    VisitorSessionClaims,
)

__all__ = [
    "INDEX_LAG_THRESHOLD",
    "ApprovalPlan",
    "AssistantTurn",
    "AvailabilityProvider",
    "BookingCommand",
    "BookingConfirmation",
    "BookingNotPermittedError",
    "BookingService",
    "Citation",
    "Claim",
    "ClaimKind",
    "ClaimValidation",
    "ClaimVerdict",
    "CommittedEffect",
    "ConflictError",
    "Contact",
    "ContactKind",
    "ContentChecksum",
    "ConversationRuntime",
    "DocumentVersion",
    "DomainError",
    "EvidenceBundle",
    "EvidenceItem",
    "EvidenceSource",
    "EvidenceUnavailableError",
    "ExpiredVisitorCredentialError",
    "ExpiryPlan",
    "GenerationStatus",
    "HandoffCommand",
    "HandoffReason",
    "HandoffService",
    "HandoffTicket",
    "HmacVisitorCredentialSigner",
    "IdempotencyKey",
    "IndexGeneration",
    "IndexIntegrityFinding",
    "IndexingFault",
    "IndexingState",
    "InvalidContactError",
    "InvalidVersionTransitionError",
    "InvalidVisitorCredentialError",
    "KnowledgeDocument",
    "KnowledgeDomain",
    "KnowledgeSource",
    "LeadCaptureNotPermittedError",
    "LeadCommand",
    "LeadReceipt",
    "LeadService",
    "LeadUrgency",
    "MissingRequiredFieldsError",
    "NotFoundError",
    "OfferedSlot",
    "PolicyViolationError",
    "PricingNotPermittedError",
    "PricingPolicy",
    "PublicDocumentView",
    "PublicTenantView",
    "PublicationPlan",
    "QuarantineReviewPlan",
    "RequiredField",
    "RetrievalAudience",
    "RetrievalContext",
    "SafetyState",
    "ServiceCatalog",
    "ServiceDefinition",
    "SlotUnavailableError",
    "SourceKind",
    "TenantPolicy",
    "TenantPolicySource",
    "ToolPermissionVerdict",
    "ToolRefusal",
    "UnknownServiceError",
    "ValidationError",
    "VersionState",
    "Visibility",
    "VisitorCredential",
    "VisitorCredentialSigner",
    "VisitorSessionClaims",
    "normalize_term",
    "sensitive_claims",
    "tool_permission",
    "validate_sensitive_claims",
]
