#!/bin/sh
# Render the site configuration from the configured upstreams, then hand the
# process to nginx.
#
# Rendering at start rather than at build keeps one immutable image usable
# against a Kubernetes Service, a compose network, and a port-forwarded backend.
set -eu

: "${CHAT_BACKEND_ORIGIN:=http://chat-admin:8004}"
: "${CHAT_ADMIN_ORIGIN:=http://chat-admin:8004}"
: "${AUTH_PROXY_ORIGIN:=http://oauth2-proxy:4180}"
: "${WIDGET_ALLOWED_ORIGINS:=}"
: "${ADMIN_GATEWAY_TOKEN:?ADMIN_GATEWAY_TOKEN is required}"

# An origin carrying a path or a stray quote would either silently rewrite every
# proxied URI or inject directives into the rendered configuration.
validate_origin() {
    printf '%s' "$2" | grep -Eq '^https?://[A-Za-z0-9._-]+(:[0-9]{1,5})?$' && return 0
    echo "$1 must be scheme://host[:port] with no trailing path, got '$2'" >&2
    exit 78
}

validate_origin CHAT_BACKEND_ORIGIN "$CHAT_BACKEND_ORIGIN"
validate_origin CHAT_ADMIN_ORIGIN "$CHAT_ADMIN_ORIGIN"
validate_origin AUTH_PROXY_ORIGIN "$AUTH_PROXY_ORIGIN"
if ! printf '%s' "$ADMIN_GATEWAY_TOKEN" | grep -Eq '^[A-Za-z0-9_-]{32,128}$'; then
    echo "ADMIN_GATEWAY_TOKEN must be 32-128 URL-safe characters" >&2
    exit 78
fi
export CHAT_BACKEND_ORIGIN CHAT_ADMIN_ORIGIN AUTH_PROXY_ORIGIN ADMIN_GATEWAY_TOKEN

# Generate the widget CORS origin map.  Each approved origin becomes a literal
# match in the nginx map directive.  An empty WIDGET_ALLOWED_ORIGINS leaves the
# map with only the default (deny-all) entry, so same-origin embeds still work
# but no cross-origin widget calls receive CORS headers.
conf_dir=/etc/nginx/conf.d
template_dir=/etc/nginx/templates

{
    printf '# Generated by entrypoint.sh from WIDGET_ALLOWED_ORIGINS.\n'
    printf '# Tightly allowlisted origins for cross-origin widget CORS.\n'
    printf '# Never wildcard; never admin origins; credential-free only.\n'
    printf 'map $http_origin $widget_cors_origin {\n'
    printf '    default "";\n'
    if [ -n "$WIDGET_ALLOWED_ORIGINS" ]; then
        OLDIFS="$IFS"
        IFS=','
        for origin in $WIDGET_ALLOWED_ORIGINS; do
            origin_trimmed="$(printf '%s' "$origin" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            [ -n "$origin_trimmed" ] || continue
            validate_origin "WIDGET_ALLOWED_ORIGINS entry" "$origin_trimmed"
            printf '    "%s" "%s";\n' "$origin_trimmed" "$origin_trimmed"
        done
        IFS="$OLDIFS"
    fi
    printf '}\n'

    # oauth2-proxy exposes the provider's groups through
    # X-Auth-Request-Groups. Map those groups to the small role vocabulary the
    # Python backend authorizes. Highest privilege wins by map order.
    printf 'map $auth_groups $auth_role {\n'
    printf '    default "";\n'
    printf '    ~*(^|[\\x20,])platform_admin([\\x20,]|$) "platform_admin";\n'
    printf '    ~*(^|[\\x20,])tenant_admin([\\x20,]|$) "tenant_admin";\n'
    printf '    ~*(^|[\\x20,])support_agent([\\x20,]|$) "support_agent";\n'
    printf '    ~*(^|[\\x20,])viewer([\\x20,]|$) "viewer";\n'
    printf '}\n'
} > "$conf_dir/widget-cors.map.conf"

# The variable list is explicit: without it envsubst would also expand nginx's
# own $uri, $host, and $proxy_add_x_forwarded_for to empty strings.
envsubst '${CHAT_BACKEND_ORIGIN} ${CHAT_ADMIN_ORIGIN} ${AUTH_PROXY_ORIGIN} ${ADMIN_GATEWAY_TOKEN}' \
    <"$template_dir/site.conf.template" \
    >"$conf_dir/site.conf"

nginx -t
exec "$@"
